import { defineConfig } from 'orval';

export default defineConfig({
  ironspot: {
    input: {
      // Generated by SpecExportTest — regenerate: cd iron-spot-api && ./gradlew test --tests "*.SpecExportTest" --rerun
      target: './openapi.json',
    },
    output: {
      mode: 'tags-split',
      target: 'src/shared/generated/api.ts',
      schemas: 'src/shared/generated/model',
      client: 'react-query',
      // Orval's `prettier: true` was tried but is a no-op in v8.9.1 even
      // without .prettierignore blocking — the `generate:api` script chains
      // `prettier --write` directly after orval instead.
      override: {
        mutator: {
          path: 'src/shared/lib/api-client.ts',
          name: 'apiClient',
        },
        query: {
          useQuery: true,
          useMutation: true,
        },
      },
    },
  },
});
