import { defineConfig } from 'orval';

export default defineConfig({
  ironspot: {
    input: {
      // Generated by SpecExportTest — regenerate: cd iron-spot-api && ./gradlew test --tests "*.SpecExportTest" --rerun
      target: './openapi.json',
      // Excluded until Task 20 adds @Operation annotations and auth hooks.
      // To include: remove this filter and re-run pnpm generate:api.
      filters: {
        tags: ['users'],
        mode: 'exclude',
      },
    },
    output: {
      mode: 'tags-split',
      target: 'src/shared/generated/api.ts',
      schemas: 'src/shared/generated/model',
      client: 'react-query',
      override: {
        mutator: {
          path: 'src/shared/lib/api-client.ts',
          name: 'apiClient',
        },
        query: {
          useQuery: true,
          useMutation: true,
        },
      },
    },
  },
});
