-- =========================================================================
-- V41 — PANATTA full catalog by series
-- =========================================================================
-- Source of truth: panattasport.com/en/catalog/ (verified 2026-05-30).
-- Replaces the 10 placeholder Panatta templates from V8 (series_id NULL)
-- with the full body-part-isolation line-up (231 machines), series-linked.
--
-- Series: Monolith/FitEvo/SEC (pin, weight-stack) and Freeweight Special
-- (plate) already exist (V27). Adds the two missing plate lines the site
-- markets: Freeweight One (32) and Fantastic (10). Freeweight HP and
-- Powerlifting hold only benches/racks/jammers (zero isolation machines
-- under scope) so they get no rows; the existing Freeweight HP series row
-- is left in place, empty.
--
-- Scope excludes cable crossovers / dual-adjustable-pulley functional
-- trainers, multi-gyms / jungle stations, Smith machines, and all benches /
-- racks / platforms / twisters. Panatta's Freeweight Special/One ISO
-- (plate-loaded leverage) machines ARE body-part machines and are included.
-- Names kept as printed on the site. FK-guarded replace; see V31.
-- =========================================================================

INSERT INTO machine_series (brand_id, name, name_ko)
SELECT b.id, s.name, s.name
FROM (VALUES ('Freeweight One'), ('Fantastic')) AS s(name)
JOIN brands b ON b.name = 'Panatta'
ON CONFLICT (brand_id, name) DO NOTHING;

DO $$
DECLARE ref_count integer;
BEGIN
  SELECT count(*) INTO ref_count
  FROM gym_machines gm
  JOIN machine_templates mt ON mt.id = gm.template_id
  JOIN brands b ON b.id = mt.brand_id
  WHERE b.name = 'Panatta';
  IF ref_count > 0 THEN
    RAISE EXCEPTION 'V41 aborted: % gym_machines still reference Panatta templates', ref_count;
  END IF;
END $$;

DELETE FROM machine_templates
WHERE brand_id = (SELECT id FROM brands WHERE name = 'Panatta');

INSERT INTO machine_templates (brand_id, category_id, name_en, name_ko, loading_type, series_id)
SELECT b.id, c.id, v.name_en, v.name_ko, v.loading::loading_type, s.id
FROM (VALUES
  ('Monolith', '등', 'Lat pulldown', '랫 풀다운', 'pin'),
  ('Monolith', '등', 'Lat pulldown circular', '랫 풀다운 서큘러', 'pin'),
  ('Monolith', '등', 'Lat pulldown convergent', '랫 풀다운 컨버전트', 'pin'),
  ('Monolith', '등', 'High row convergent', '하이 로우 컨버전트', 'pin'),
  ('Monolith', '등', 'Pulley row', '풀리 로우', 'pin'),
  ('Monolith', '등', 'Rowing machine circular', '로잉 머신 서큘러', 'pin'),
  ('Monolith', '등', 'Lower back', '로워 백', 'pin'),
  ('Monolith', '등', 'Pullover machine', '풀오버 머신', 'pin'),
  ('Monolith', '가슴', 'Vertical chest press circular', '버티컬 체스트 프레스 서큘러', 'pin'),
  ('Monolith', '가슴', 'Inclined chest press circular', '인클라인 체스트 프레스 서큘러', 'pin'),
  ('Monolith', '가슴', 'Pectoral machine', '펙토럴 머신', 'pin'),
  ('Monolith', '가슴', 'Peck back', '펙 백', 'pin'),
  ('Monolith', '어깨', 'Deltoid press circular', '델토이드 프레스 서큘러', 'pin'),
  ('Monolith', '어깨', 'Lateral deltoid', '래터럴 델토이드', 'pin'),
  ('Monolith', '팔', 'Dips press', '딥스 프레스', 'pin'),
  ('Monolith', '팔', 'French press machine', '프렌치 프레스 머신', 'pin'),
  ('Monolith', '팔', 'Triceps machine', '트라이셉스 머신', 'pin'),
  ('Monolith', '팔', 'Alternate arm extension', '얼터네이트 암 익스텐션', 'pin'),
  ('Monolith', '팔', 'Curling machine', '컬링 머신', 'pin'),
  ('Monolith', '팔', 'Alternate arm curl', '얼터네이트 암 컬', 'pin'),
  ('Monolith', '팔', 'Standing total arms', '스탠딩 토탈 암', 'pin'),
  ('Monolith', '코어', 'Abdominal crunch', '업도미널 크런치', 'pin'),
  ('Monolith', '하체', 'Leg extension', '레그 익스텐션', 'pin'),
  ('Monolith', '하체', 'Leg curling', '레그 컬링', 'pin'),
  ('Monolith', '하체', 'Seated leg curling', '시티드 레그 컬링', 'pin'),
  ('Monolith', '하체', 'Horizontal adjustable leg press', '호리존탈 어저스터블 레그 프레스', 'pin'),
  ('Monolith', '하체', 'Abductor machine', '어브덕터 머신', 'pin'),
  ('Monolith', '하체', 'Adductor machine', '어덕터 머신', 'pin'),
  ('Monolith', '하체', 'Dual adductor abductor machine', '듀얼 어덕터 어브덕터 머신', 'pin'),
  ('Monolith', '하체', 'Master gluteus plus', '마스터 글루테우스 플러스', 'pin'),
  ('Monolith', '하체', 'Gluteus machine', '글루테우스 머신', 'pin'),
  ('Monolith', '하체', 'Hip thrust', '힙 트러스트', 'pin'),
  ('Monolith', '하체', 'Calf hack machine', '카프 핵 머신', 'pin'),
  ('Monolith', '하체', 'Multi hip', '멀티 힙', 'pin'),
  ('Monolith', '하체', 'Standing abductor', '스탠딩 어브덕터', 'pin'),
  ('Monolith', '하체', 'Standing multi flight', '스탠딩 멀티 플라이트', 'pin'),
  ('FitEvo', '등', 'Lat pulldown', '랫 풀다운', 'pin'),
  ('FitEvo', '등', 'Lat pulldown double stack', '랫 풀다운 더블 스택', 'pin'),
  ('FitEvo', '등', 'Lat pulldown circular', '랫 풀다운 서큘러', 'pin'),
  ('FitEvo', '등', 'Lat pulldown convergent', '랫 풀다운 컨버전트', 'pin'),
  ('FitEvo', '등', 'High row convergent', '하이 로우 컨버전트', 'pin'),
  ('FitEvo', '등', 'Pulley row', '풀리 로우', 'pin'),
  ('FitEvo', '등', 'Pulley row double stack', '풀리 로우 더블 스택', 'pin'),
  ('FitEvo', '등', 'Rowing machine circular', '로잉 머신 서큘러', 'pin'),
  ('FitEvo', '등', 'Total back', '토탈 백', 'pin'),
  ('FitEvo', '등', 'Lower back', '로워 백', 'pin'),
  ('FitEvo', '등', 'Pullover machine', '풀오버 머신', 'pin'),
  ('FitEvo', '가슴', 'Pectoral machine', '펙토럴 머신', 'pin'),
  ('FitEvo', '가슴', 'Vertical chest press', '버티컬 체스트 프레스', 'pin'),
  ('FitEvo', '가슴', 'Vertical chest press circular', '버티컬 체스트 프레스 서큘러', 'pin'),
  ('FitEvo', '가슴', 'Inclined chest press', '인클라인 체스트 프레스', 'pin'),
  ('FitEvo', '가슴', 'Inclined chest press circular', '인클라인 체스트 프레스 서큘러', 'pin'),
  ('FitEvo', '가슴', 'Peck back', '펙 백', 'pin'),
  ('FitEvo', '가슴', 'Total press', '토탈 프레스', 'pin'),
  ('FitEvo', '가슴', 'Multipurpose press', '멀티퍼포즈 프레스', 'pin'),
  ('FitEvo', '어깨', 'Deltoid press', '델토이드 프레스', 'pin'),
  ('FitEvo', '어깨', 'Deltoid press circular', '델토이드 프레스 서큘러', 'pin'),
  ('FitEvo', '어깨', 'Lateral deltoids', '래터럴 델토이드', 'pin'),
  ('FitEvo', '어깨', 'Rotary cuff', '로테이터 커프', 'pin'),
  ('FitEvo', '팔', 'Dips press', '딥스 프레스', 'pin'),
  ('FitEvo', '팔', 'French press machine', '프렌치 프레스 머신', 'pin'),
  ('FitEvo', '팔', 'Triceps machine', '트라이셉스 머신', 'pin'),
  ('FitEvo', '팔', 'Alternate arm extension', '얼터네이트 암 익스텐션', 'pin'),
  ('FitEvo', '팔', 'Alternate arm extension 90', '얼터네이트 암 익스텐션 90', 'pin'),
  ('FitEvo', '팔', 'Alternate pronating triceps', '얼터네이트 프로네이팅 트라이셉스', 'pin'),
  ('FitEvo', '팔', 'Curling machine', '컬링 머신', 'pin'),
  ('FitEvo', '팔', 'Alternate arm curl', '얼터네이트 암 컬', 'pin'),
  ('FitEvo', '팔', 'Alternate arm curl 120', '얼터네이트 암 컬 120', 'pin'),
  ('FitEvo', '팔', 'Alternate arm curl -45', '얼터네이트 암 컬 -45', 'pin'),
  ('FitEvo', '팔', 'Alternate preacher curl machine', '얼터네이트 프리처 컬 머신', 'pin'),
  ('FitEvo', '팔', 'Alternate supinating biceps', '얼터네이트 수피네이팅 바이셉스', 'pin'),
  ('FitEvo', '팔', 'Standing total arms', '스탠딩 토탈 암', 'pin'),
  ('FitEvo', '팔', 'Alternate standing total arms', '얼터네이트 스탠딩 토탈 암', 'pin'),
  ('FitEvo', '코어', 'Upper abdominal', '어퍼 업도미널', 'pin'),
  ('FitEvo', '코어', 'Abdominal crunch', '업도미널 크런치', 'pin'),
  ('FitEvo', '코어', 'Torsion machine', '토션 머신', 'pin'),
  ('FitEvo', '하체', 'Leg extension', '레그 익스텐션', 'pin'),
  ('FitEvo', '하체', 'Leg curling', '레그 컬링', 'pin'),
  ('FitEvo', '하체', 'Seated leg curling', '시티드 레그 컬링', 'pin'),
  ('FitEvo', '하체', 'Standing leg curling', '스탠딩 레그 컬링', 'pin'),
  ('FitEvo', '하체', 'Dual system horizontal leg press', '듀얼 시스템 호리존탈 레그 프레스', 'pin'),
  ('FitEvo', '하체', 'Horizontal leg press', '호리존탈 레그 프레스', 'pin'),
  ('FitEvo', '하체', 'Abductor machine', '어브덕터 머신', 'pin'),
  ('FitEvo', '하체', 'Adductor machine', '어덕터 머신', 'pin'),
  ('FitEvo', '하체', 'Adductor abductor machine', '어덕터 어브덕터 머신', 'pin'),
  ('FitEvo', '하체', 'Master gluteus plus', '마스터 글루테우스 플러스', 'pin'),
  ('FitEvo', '하체', 'Gluteus machine', '글루테우스 머신', 'pin'),
  ('FitEvo', '하체', 'Hip thrust', '힙 트러스트', 'pin'),
  ('FitEvo', '하체', 'Standing hip thrust', '스탠딩 힙 트러스트', 'pin'),
  ('FitEvo', '하체', 'Calf machine', '카프 머신', 'pin'),
  ('FitEvo', '하체', 'Standing abductor machine', '스탠딩 어브덕터 머신', 'pin'),
  ('FitEvo', '하체', 'Multi hip', '멀티 힙', 'pin'),
  ('FitEvo', '하체', 'Power runner', '파워 러너', 'pin'),
  ('FitEvo', '하체', 'Standing multi flight', '스탠딩 멀티 플라이트', 'pin'),
  ('SEC', '등', 'Lat pulldown', '랫 풀다운', 'pin'),
  ('SEC', '등', 'Pulley row', '풀리 로우', 'pin'),
  ('SEC', '등', 'Rowing machine', '로잉 머신', 'pin'),
  ('SEC', '등', 'Lower back', '로워 백', 'pin'),
  ('SEC', '가슴', 'Vertical chest convergent', '버티컬 체스트 컨버전트', 'pin'),
  ('SEC', '가슴', 'Inclined chest press', '인클라인 체스트 프레스', 'pin'),
  ('SEC', '가슴', 'Pectoral machine', '펙토럴 머신', 'pin'),
  ('SEC', '가슴', 'Peck back', '펙 백', 'pin'),
  ('SEC', '어깨', 'Deltoid press convergent', '델토이드 프레스 컨버전트', 'pin'),
  ('SEC', '팔', 'Curling machine', '컬링 머신', 'pin'),
  ('SEC', '팔', 'Triceps machine', '트라이셉스 머신', 'pin'),
  ('SEC', '코어', 'Upper abdominal', '어퍼 업도미널', 'pin'),
  ('SEC', '하체', 'Leg extension', '레그 익스텐션', 'pin'),
  ('SEC', '하체', 'Leg curling', '레그 컬링', 'pin'),
  ('SEC', '하체', 'Seated leg curling', '시티드 레그 컬링', 'pin'),
  ('SEC', '하체', 'Horizontal leg press', '호리존탈 레그 프레스', 'pin'),
  ('SEC', '하체', 'Horizontal leg press medical', '호리존탈 레그 프레스 메디컬', 'pin'),
  ('SEC', '하체', 'Abductor machine', '어브덕터 머신', 'pin'),
  ('SEC', '하체', 'Adductor machine', '어덕터 머신', 'pin'),
  ('SEC', '하체', 'Adductor abductor machine', '어덕터 어브덕터 머신', 'pin'),
  ('SEC', '하체', 'Calf machine', '카프 머신', 'pin'),
  ('SEC', '하체', 'Multi hip', '멀티 힙', 'pin'),
  ('SEC', '등', 'Dual lat machine / pulley row', '듀얼 랫 머신 / 풀리 로우', 'pin'),
  ('SEC', '가슴', 'Dual chest press / rowing machine convergent', '듀얼 체스트 프레스 / 로잉 머신 컨버전트', 'pin'),
  ('SEC', '팔', 'Dual curling / triceps machine', '듀얼 컬링 / 트라이셉스 머신', 'pin'),
  ('SEC', '코어', 'Dual abdominal / lower back', '듀얼 업도미널 / 로워 백', 'pin'),
  ('SEC', '하체', 'Dual leg extension / seated leg curling', '듀얼 레그 익스텐션 / 시티드 레그 컬링', 'pin'),
  ('Freeweight Special', '등', 'Super lat machine convergent', '슈퍼 랫 머신 컨버전트', 'plate'),
  ('Freeweight Special', '등', 'Super lat pulldown circular', '슈퍼 랫 풀다운 서큘러', 'plate'),
  ('Freeweight Special', '등', 'Super high row', '슈퍼 하이 로우', 'plate'),
  ('Freeweight Special', '등', 'Super power row', '슈퍼 파워 로우', 'plate'),
  ('Freeweight Special', '등', 'Super low row', '슈퍼 로우 로우', 'plate'),
  ('Freeweight Special', '등', 'Super rowing', '슈퍼 로잉', 'plate'),
  ('Freeweight Special', '등', 'Super rowing circular', '슈퍼 로잉 서큘러', 'plate'),
  ('Freeweight Special', '등', 'T-bar row', '티바 로우', 'plate'),
  ('Freeweight Special', '등', 'Super dorsy bar', '슈퍼 도시 바', 'plate'),
  ('Freeweight Special', '등', 'Front dorsy bar', '프론트 도시 바', 'plate'),
  ('Freeweight Special', '등', 'Super pullover machine', '슈퍼 풀오버 머신', 'plate'),
  ('Freeweight Special', '등', 'Pullover machine', '풀오버 머신', 'plate'),
  ('Freeweight Special', '가슴', 'Super vertical chest press', '슈퍼 버티컬 체스트 프레스', 'plate'),
  ('Freeweight Special', '가슴', 'Super inclined chest press', '슈퍼 인클라인 체스트 프레스', 'plate'),
  ('Freeweight Special', '가슴', 'Super declined chest press', '슈퍼 디클라인 체스트 프레스', 'plate'),
  ('Freeweight Special', '가슴', 'Super horizontal bench press', '슈퍼 호리존탈 벤치 프레스', 'plate'),
  ('Freeweight Special', '가슴', 'Super inclined bench press', '슈퍼 인클라인 벤치 프레스', 'plate'),
  ('Freeweight Special', '가슴', 'Super middle chest flight machine', '슈퍼 미들 체스트 플라이트 머신', 'plate'),
  ('Freeweight Special', '가슴', 'Super upper chest flight machine', '슈퍼 어퍼 체스트 플라이트 머신', 'plate'),
  ('Freeweight Special', '가슴', 'Super lower chest flight machine', '슈퍼 로워 체스트 플라이트 머신', 'plate'),
  ('Freeweight Special', '가슴', 'Super horizontal multi press', '슈퍼 호리존탈 멀티 프레스', 'plate'),
  ('Freeweight Special', '가슴', 'Super vertical multi press', '슈퍼 버티컬 멀티 프레스', 'plate'),
  ('Freeweight Special', '가슴', 'Dips press dual system', '딥스 프레스 듀얼 시스템', 'plate'),
  ('Freeweight Special', '가슴', 'Dips press', '딥스 프레스', 'plate'),
  ('Freeweight Special', '가슴', 'Super peck back', '슈퍼 펙 백', 'plate'),
  ('Freeweight Special', '어깨', 'Super deltoid press', '슈퍼 델토이드 프레스', 'plate'),
  ('Freeweight Special', '어깨', 'Lateral deltoids', '래터럴 델토이드', 'plate'),
  ('Freeweight Special', '어깨', 'Back deltoids', '백 델토이드', 'plate'),
  ('Freeweight Special', '어깨', 'Super shrug machine', '슈퍼 슈러그 머신', 'plate'),
  ('Freeweight Special', '어깨', 'Viking press and calf', '바이킹 프레스 앤 카프', 'plate'),
  ('Freeweight Special', '팔', 'Super french press machine', '슈퍼 프렌치 프레스 머신', 'plate'),
  ('Freeweight Special', '팔', 'Alternate triceps machine', '얼터네이트 트라이셉스 머신', 'plate'),
  ('Freeweight Special', '팔', 'Triceps machine', '트라이셉스 머신', 'plate'),
  ('Freeweight Special', '팔', 'Three angles triceps machine', '쓰리 앵글 트라이셉스 머신', 'plate'),
  ('Freeweight Special', '팔', 'Alternate curling machine', '얼터네이트 컬링 머신', 'plate'),
  ('Freeweight Special', '팔', 'Curling machine', '컬링 머신', 'plate'),
  ('Freeweight Special', '팔', 'Three angles biceps machine', '쓰리 앵글 바이셉스 머신', 'plate'),
  ('Freeweight Special', '팔', 'Four angle biceps machines', '포 앵글 바이셉스 머신', 'plate'),
  ('Freeweight Special', '팔', 'Alternate arm curl 120', '얼터네이트 암 컬 120', 'plate'),
  ('Freeweight Special', '팔', 'Alternate arm curl -45', '얼터네이트 암 컬 -45', 'plate'),
  ('Freeweight Special', '팔', 'Alternate preacher curl machine', '얼터네이트 프리처 컬 머신', 'plate'),
  ('Freeweight Special', '코어', 'Total core crunch machine', '토탈 코어 크런치 머신', 'plate'),
  ('Freeweight Special', '하체', 'Super leg press bridge', '슈퍼 레그 프레스 브릿지', 'plate'),
  ('Freeweight Special', '하체', 'Super horizontal leg press dual system', '슈퍼 호리존탈 레그 프레스 듀얼 시스템', 'plate'),
  ('Freeweight Special', '하체', 'Super leg press 45', '슈퍼 레그 프레스 45', 'plate'),
  ('Freeweight Special', '하체', 'Super leg press 45 dual system', '슈퍼 레그 프레스 45 듀얼 시스템', 'plate'),
  ('Freeweight Special', '하체', 'Super vertical leg press', '슈퍼 버티컬 레그 프레스', 'plate'),
  ('Freeweight Special', '하체', 'Vertical leg press', '버티컬 레그 프레스', 'plate'),
  ('Freeweight Special', '하체', 'Super squat machine', '슈퍼 스쿼트 머신', 'plate'),
  ('Freeweight Special', '하체', 'Super power squat', '슈퍼 파워 스쿼트', 'plate'),
  ('Freeweight Special', '하체', 'Super pendulum squat', '슈퍼 펜듈럼 스쿼트', 'plate'),
  ('Freeweight Special', '하체', 'Belt squat', '벨트 스쿼트', 'plate'),
  ('Freeweight Special', '하체', 'Super hack squat', '슈퍼 핵 스쿼트', 'plate'),
  ('Freeweight Special', '하체', 'Super lunge machine', '슈퍼 런지 머신', 'plate'),
  ('Freeweight Special', '하체', 'Super calf hack', '슈퍼 카프 핵', 'plate'),
  ('Freeweight Special', '하체', 'Super seated calf', '슈퍼 시티드 카프', 'plate'),
  ('Freeweight Special', '하체', 'Donkey calf', '동키 카프', 'plate'),
  ('Freeweight Special', '하체', 'Power runner', '파워 러너', 'plate'),
  ('Freeweight Special', '하체', 'Hip thrust', '힙 트러스트', 'plate'),
  ('Freeweight Special', '하체', 'Standing abductor', '스탠딩 어브덕터', 'plate'),
  ('Freeweight Special', '하체', '3D abductor', '3D 어브덕터', 'plate'),
  ('Freeweight Special', '하체', 'Leg extension', '레그 익스텐션', 'plate'),
  ('Freeweight Special', '하체', 'Alternate leg extension', '얼터네이트 레그 익스텐션', 'plate'),
  ('Freeweight Special', '하체', 'Alternate leg curling', '얼터네이트 레그 컬링', 'plate'),
  ('Freeweight Special', '하체', 'Leg curling', '레그 컬링', 'plate'),
  ('Freeweight Special', '하체', 'Seated leg curling', '시티드 레그 컬링', 'plate'),
  ('Freeweight Special', '하체', 'Kneeling leg curling', '닐링 레그 컬링', 'plate'),
  ('Freeweight Special', '하체', 'Reverse hyperextension', '리버스 하이퍼익스텐션', 'plate'),
  ('Freeweight One', '등', 'Lat machine convergent', '랫 머신 컨버전트', 'plate'),
  ('Freeweight One', '등', 'Lat pulldown circular', '랫 풀다운 서큘러', 'plate'),
  ('Freeweight One', '등', 'Rowing machine', '로잉 머신', 'plate'),
  ('Freeweight One', '등', 'Low row', '로우 로우', 'plate'),
  ('Freeweight One', '등', 'Power row', '파워 로우', 'plate'),
  ('Freeweight One', '등', 'High row', '하이 로우', 'plate'),
  ('Freeweight One', '등', 'Adjustable row 45', '어저스터블 로우 45', 'plate'),
  ('Freeweight One', '등', 'Dorsy bar', '도시 바', 'plate'),
  ('Freeweight One', '등', 'Pullover machine', '풀오버 머신', 'plate'),
  ('Freeweight One', '가슴', 'Vertical chest press', '버티컬 체스트 프레스', 'plate'),
  ('Freeweight One', '가슴', 'Inclined chest press', '인클라인 체스트 프레스', 'plate'),
  ('Freeweight One', '가슴', 'Middle chest flight machine', '미들 체스트 플라이트 머신', 'plate'),
  ('Freeweight One', '가슴', 'Upper chest flight machine', '어퍼 체스트 플라이트 머신', 'plate'),
  ('Freeweight One', '가슴', 'Dips press', '딥스 프레스', 'plate'),
  ('Freeweight One', '어깨', 'Vertical multi press', '버티컬 멀티 프레스', 'plate'),
  ('Freeweight One', '어깨', 'Deltoid press', '델토이드 프레스', 'plate'),
  ('Freeweight One', '어깨', 'Lateral deltoids', '래터럴 델토이드', 'plate'),
  ('Freeweight One', '어깨', 'Back deltoids', '백 델토이드', 'plate'),
  ('Freeweight One', '어깨', 'Shrug machine', '슈러그 머신', 'plate'),
  ('Freeweight One', '팔', 'Curling machine', '컬링 머신', 'plate'),
  ('Freeweight One', '팔', 'French press machine', '프렌치 프레스 머신', 'plate'),
  ('Freeweight One', '하체', 'Leg press bridge', '레그 프레스 브릿지', 'plate'),
  ('Freeweight One', '하체', 'Leg press 45', '레그 프레스 45', 'plate'),
  ('Freeweight One', '하체', 'Hack squat', '핵 스쿼트', 'plate'),
  ('Freeweight One', '하체', 'Pendulum squat', '펜듈럼 스쿼트', 'plate'),
  ('Freeweight One', '하체', 'Squat and calf machine', '스쿼트 앤 카프 머신', 'plate'),
  ('Freeweight One', '하체', 'Seated calf', '시티드 카프', 'plate'),
  ('Freeweight One', '하체', 'Leg extension', '레그 익스텐션', 'plate'),
  ('Freeweight One', '하체', 'Seated leg curling', '시티드 레그 컬링', 'plate'),
  ('Freeweight One', '하체', 'Kneeling leg curling', '닐링 레그 컬링', 'plate'),
  ('Freeweight One', '하체', 'Hip thrust', '힙 트러스트', 'plate'),
  ('Freeweight One', '하체', 'Standing hip thrust', '스탠딩 힙 트러스트', 'plate'),
  ('Fantastic', '등', 'Lat machine', '랫 머신', 'plate'),
  ('Fantastic', '등', 'Pullover machine', '풀오버 머신', 'plate'),
  ('Fantastic', '가슴', 'Vertical multi press', '버티컬 멀티 프레스', 'plate'),
  ('Fantastic', '가슴', 'Vertical pek dek', '버티컬 펙 덱', 'plate'),
  ('Fantastic', '가슴', 'Peck back', '펙 백', 'plate'),
  ('Fantastic', '팔', 'Biceps machine', '바이셉스 머신', 'plate'),
  ('Fantastic', '팔', 'Triceps machine', '트라이셉스 머신', 'plate'),
  ('Fantastic', '하체', 'Leg extension', '레그 익스텐션', 'plate'),
  ('Fantastic', '하체', 'Leg press 45', '레그 프레스 45', 'plate'),
  ('Fantastic', '하체', 'Squat and calf machine', '스쿼트 앤 카프 머신', 'plate')
) AS v(series_name, cat_name, name_en, name_ko, loading)
JOIN brands b ON b.name = 'Panatta'
JOIN categories c ON c.name = v.cat_name
JOIN machine_series s ON s.brand_id = b.id AND s.name = v.series_name;
