spring:
  application:
    name: iron-spot-api
  main:
    web-application-type: servlet
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 3MB
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USERNAME:}
    password: ${DATABASE_PASSWORD:}

security:
  supabase-jwt-secret: ${SUPABASE_JWT_SECRET}

supabase:
  url: ${SUPABASE_URL}
  service-role-key: ${SUPABASE_SERVICE_ROLE_KEY}

google:
  vision:
    api-key: ${GOOGLE_VISION_API_KEY:}

naver:
  maps:
    client-id: ${NAVER_MAPS_CLIENT_ID}
    client-secret: ${NAVER_MAPS_CLIENT_SECRET}

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info
  info:
    env:
      enabled: true

info:
  app:
    version: '@project.version@'
